### ISSUE TITLE
calculation issue

### ISSUE THREAD

**Issue by 994422** [endixk/ezaai#20]
Hello,
I tried using EzAAI for a calculation. The first time, it worked without any issues, but I encountered an error on my second attempt. Can you explain what the 'mm.label' file is? Here's what my terminal showed:
This is my code: java -jar EzAAI.jar calculate -i db/ -j mmseqs/ -o out/aai.tsv

java.io.FileNotFoundException: mm.label (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at leb.main.EzAAI.runCalculate(EzAAI.java:456)
	at leb.main.EzAAI.run(EzAAI.java:689)
	at leb.main.EzAAI.main(EzAAI.java:725)
[MAR 03 01:26:15] ERROR   |:  Program terminated with error.

I would appreciate your assistance in resolving this issue. 
Thanks.

**Comment by endixk** [comment]
Hi,

mm.label is a text file that is included in the database, which indicates the name of the database and should exist in a database properly generated with either `extract` or `convert` methods.

I suppose one or more of your input directories contains a file (or files) that is not a database or a corrupted one.

**Comment by endixk** [comment]
No probs! The pipeline is scalable without explicit limit to the number of files, therefore you can provide as many databases as you want in a single batch of calculation. I suppose the major bottleneck will be the computation time.

**Comment by ggavelis** [comment]
I also have this issue. I'm using ezaai v1.2.4 (conda installation), and running the **extract** followed by the **calculate** command.

Where is the mm.label file supposed to be created? When I use **extract**, it creates a directory containing only *.db files.

Thank you,  ~Greg

**Comment by endixk** [comment]
Hello @ggavelis, sorry for the late reply.

`mm.label` is an internal file compressed in the database, so if everything runs smoothly, you're not supposed to see that file. The `calculate` module works directly on *.db files created by the `extract` module.
