### ISSUE TITLE
calculation issue java.io.IOException: Cannot delete file: /tmp/ezaai/78e2b9bcc9dd8cf6_tmp/8191412700641163904

### ISSUE THREAD

**Issue by caizhangbin** [endixk/ezaai#23]
Hi developers, I ran the program but got his error. 
[MAR 15 12:15:10] EzAAI   |:  EzAAI - v1.2.3 [Feb. 2024]
[MAR 15 12:15:20] EzAAI   |:  Calculating AAI... [Task 1/484]
org.apache.commons.io.IOExceptionList: /tmp/ezaai/78e2b9bcc9dd8cf6_tmp
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
	at leb.process.ProcCalcPairwiseAAI.pairwiseMmseqs(ProcCalcPairwiseAAI.java:399)
	at leb.process.ProcCalcPairwiseAAI.calculateProteomePairWithDetails(ProcCalcPairwiseAAI.java:67)
	at leb.main.EzAAI.runCalculate(EzAAI.java:511)
	at leb.main.EzAAI.run(EzAAI.java:689)
	at leb.main.EzAAI.main(EzAAI.java:725)
Caused by: java.io.IOException: Cannot delete file: /tmp/ezaai/78e2b9bcc9dd8cf6_tmp/8191412700641163904
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /tmp/ezaai/78e2b9bcc9dd8cf6_tmp/8191412700641163904/pref_0.dbtype
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:291)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:109)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:161)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2786)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2857)
	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
	... 7 more
[MAR 15 12:15:24] ERROR   |:  Program terminated with error.

Any suggestions?

**Comment by endixk** [comment]
Hi, it seems like a duplicate issue with #21.

Please refer to the solution I wrote there: https://github.com/endixk/ezaai/issues/21#issuecomment-1989971561
