### ISSUE TITLE
Ezaai calculate issue

### ISSUE THREAD

**Issue by AleksandarStan** [endixk/ezaai#24]
Hello developers,

I'm trying to test the program for AAI calculation and I stumbled upon an issue when I tried to execute the calculate module. The program was installed with Conda and I can create a database file fine. I ran the following command:
ezaai calculate -i db/ -j db/ -o aai.tsv

I got this:
[APR 08 06:16:16] EzAAI   |:  EzAAI - v1.2.3 [Feb. 2024]
java.io.FileNotFoundException: mm.label (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at leb.main.EzAAI.runCalculate(EzAAI.java:456)
        at leb.main.EzAAI.run(EzAAI.java:689)
        at leb.main.EzAAI.main(EzAAI.java:725)

I also tried giving the -tmp argument to the command and the same error appeared.
Any ideas on how to solve this?

/Aleks

**Comment by AleksandarStan** [comment]
Hello,

After a closer inspection of my database files, I realized that some of them were indeed corrupted. After repeating extract command, databases were correct, and the calculate command was executed smoothly.

Thank you for the help!
